version: "2.1"
services:
  worker1:
    build: ./build
    privileged: true
    environment:
      - OBS_SRC_SERVER="build.parrotsec.org:5352"
      - OBS_REPO_SERVERS="build.parrotsec.org:5252"
      - OBS_WORKER_INSTANCES="1"
      - OBS_WORKER_JOBS="4"
      - OBS_WORKER_INSTANCE_NAMES="WORKER10"
  worker2:
    build: ./build
    privileged: true
    environment:
      - OBS_SRC_SERVER="build.parrotsec.org:5352"
      - OBS_REPO_SERVERS="build.parrotsec.org:5252"
      - OBS_WORKER_INSTANCES="1"
      - OBS_WORKER_JOBS="4"
      - OBS_WORKER_INSTANCE_NAMES="WORKER11"
