version: "2.1"
services:
  worker1:
    build: ./build
    privileged: true
    network_mode: host
    environment:
      - OBS_SRC_SERVER="build.parrotsec.org"
      - OBS_REPO_SERVERS="build.parrotsec.org"
      - OBS_WORKER_INSTANCES="2"
      - OBS_WORKER_JOBS="4"
      - OBS_WORKER_INSTANCE_NAMES="WORKER10"
